name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Vanilla
      run: |
        wget https://files.catbox.moe/jeu7gx.zip -O Vanilla.zip
        unzip Vanilla.zip
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Setup ms-build
      run: sudo apt-get install -y nuget mono-devel mono-xbuild
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build PrePatcher -o PrePatcher/Output -p:Configuration=Release
        dotnet build Assembly-CSharp -p:SolutionDir=$PWD -p:Configuration=Release
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: ModdingApi
        path: ./OutputFinal/
