name: .NET

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master, ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: HollowKnight-Modding/Vanilla-CI-Refs
        ssh-key: ${{ secrets.VANILLA_DEPLOY_KEY }}
        ref: master
        path: Vanilla
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Setup ms-build
      run: sudo apt-get install -y nuget mono-devel mono-xbuild
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build PrePatcher -o PrePatcher/Output -p:Configuration=Release
        dotnet build Assembly-CSharp -p:SolutionDir=$PWD -p:Configuration=Release
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: ModdingApi
        path: ./OutputFinal/
