name: .NET

on:
  push:
    branches: [ master, ci, docs ]
  pull_request:
    branches: [ master, ci ]

jobs:
  build-win:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Vanilla
      run: |
        wget https://files.catbox.moe/b7ulxr.zip -O Vanilla.zip
        unzip Vanilla.zip -d Vanilla
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Setup ms-build
      run: sudo apt-get install -y nuget mono-devel mono-xbuild
    - name: Restore dependencies
      run: dotnet restore
    - name: Build PrePatcher
      run: |
        dotnet build PrePatcher -o PrePatcher/Output -p:Configuration=Release
    - name: Build Assembly-CSharp (Windows)
      run: |
        dotnet build Assembly-CSharp -p:SolutionDir=$PWD -p:Configuration=Release
    - name: Upload Windows Binary
      uses: actions/upload-artifact@v2
      with:
        name: ModdingApiWin
        path: ./OutputFinal/

  build-unix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Vanilla
      run: |
        wget https://files.catbox.moe/998qrb.zip -O Vanilla.zip
        unzip Vanilla.zip -d Vanilla
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Setup ms-build
      run: sudo apt-get install -y nuget mono-devel mono-xbuild
    - name: Restore dependencies
      run: dotnet restore
    - name: Build PrePatcher
      run: |
        dotnet build PrePatcher -o PrePatcher/Output -p:Configuration=Release
    - name: Build Assembly-CSharp 
      run: |
        dotnet build Assembly-CSharp -p:SolutionDir=$PWD -p:Configuration=Release
    - name: Upload Unix-like Binary
      uses: actions/upload-artifact@v2
      with:
        name: ModdingApiUnix
        path: ./OutputFinal/
  docfx:
    needs: [build-win, build-unix]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: docs
          path: docs
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: Setup ms-build, mono
        run: sudo apt-get install -y nuget mono-devel mono-xbuild
      - name: Download DocFX
        working-directory: docs
        run: |
          wget https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -O docfx.zip
          unzip docfx.zip -d docfx
      - name: Build docs
        working-directory: docs
        run: |
          mono docfx/docfx.exe 
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: DocFX
          force_orphan: true
